#
# Copyright (c) 2001-2016 Primeton Technologies, Ltd.
# All rights reserved.
#
# author: ZhongWen Li (mailto:lizw@primeton.com)
#

FROM euler-registry.primeton.com/frontapp

MAINTAINER www.primeton.com, registry@primeton.com

ADD ./resources/ ${APP_HOME}/
