#
# Copyright (c) 2001-2016 Primeton Technologies, Ltd.
# All rights reserved.
#
# author: ZhongWen Li (mailto:lizw@primeton.com)
#

FROM euler-registry.primeton.com/jetty9

MAINTAINER www.primeton.com, registry@primeton.com

# If Dockerfile in WAR root directory
ADD ./resources/war/ ${JETTY_HOME}/webapps/ROOT/
