#
# Copyright (c) 2001-2016 Primeton Technologies, Ltd.
# All rights reserved.
#
# author: ZhongWen Li (mailto:lizw@primeton.com)
#

FROM capttofu/percona_xtradb_cluster_5_6:beta
# euler-registry.primeton.com/FROM capttofu/percona_xtradb_cluster_5_6:beta

MAINTAINER www.primeton.com, registry@primeton.com

COPY resources/entrypoint.sh /entrypoint.sh
