#
# Copyright (c) 2001-2016 Primeton Technologies, Ltd.
# All rights reserved.
#
# author: ZhongWen Li (mailto:lizw@primeton.com)
#

FROM euler-registry.primeton.com/springboot

# Copy runnable jar file
ADD ./resources/target/runnable-jar-example-1.0.0-jar-with-dependencies.jar ${APP_HOME}/lib/bootstrap.jar
