#
# Copyright (c) 2001-2016 Primeton Technologies, Ltd.
# All rights reserved.
#
# author: ZhongWen Li (mailto:lizw@primeton.com)
#

# FROM docker.io/redis:3.2.1
FROM redis:3.2.1

MAINTAINER www.primeton.com, registry@primeton.com
